services:
  api:
    build:
      context: ./api
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      storage:
        condition: service_healthy
    env_file: .env
    environment:
      DB_HOST: db
      STORAGE_HOST: storage
      STORAGE_PUBLIC_URL: ${STORAGE_PUBLIC_URL:-http://localhost:9000}
    ports:
      - "127.0.0.1:8080:8080"

  frontend:
    build:
      context: ./frontend
    restart: on-failure
    ports:
      - "127.0.0.1:3000:80"

  vector-index:
    build:
      context: ./vector-index
    restart: on-failure
    env_file: .env
    volumes:
      - ./documents:/documents
    environment:
      LEANN_OLLAMA_HOST: "http://ollama-server:11434"
      LEANN_BACKEND: hnsw
      DB_HOST: db
      STORAGE_HOST: storage
    depends_on:
      db:
        condition: service_healthy
      storage:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    # volumes:
    #   - ./indexes:/app/src/.leann/indexes

  ollama-server:
    image: ollama/ollama:0.21.0
    restart: on-failure
    ports:
      - "127.0.0.1:11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_CONTEXT_LENGTH=32768
      - OLLAMA_KEEP_ALIVE=1h
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LLM_MODEL=${LLM_MODEL}
      - TRANSLATOR_MODEL=${TRANSLATOR_MODEL}
    volumes:
      - ./ollama-data:/root/.ollama
      - ./ollama-server/entrypoint.sh:/entrypoint.sh
      - ./ollama-server/Modelfile-embeddings-cpu:/models/Modelfile-embeddings-cpu
      - ./ollama-server/Modelfile-llm-gpu:/models/Modelfile-llm-gpu
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash",
          "-c",
          "{ printf >&3 'GET / HTTP/1.0\\r\\n\\r\\n'; cat <&3; } 3<>/dev/tcp/localhost/11434 | grep 'Ollama is' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

  db:
    image: postgres:16
    restart: on-failure
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USR}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U ${DB_USR} -d ${DB_NAME}
      interval: 10s
      timeout: 3s
      retries: 3

  db-dashboard:
    restart: unless-stopped
    image: sosedoff/pgweb:0.17.0
    ports:
      - 8081:8081
    environment:
      - PGWEB_DATABASE_URL=postgres://${DB_USR}:${DB_PWD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  storage:
    image: chrislusf/seaweedfs:4.20
    # image: rustfs/rustfs:1.0.0-alpha.95
    ports:
      - "127.0.0.1:9000:9000" # S3 API
      - "127.0.0.1:9333:9333" # Server Status
      - "127.0.0.1:8888:8888" # WebUI
    volumes:
      - ./seaweed-server/filer.toml:/etc/seaweedfs/filer.toml
      - ./seaweed-server/s3-config.json:/etc/seaweedfs/s3-config.json
      # - ./sw_data:/data
    command: >
      server 
      -ip=storage
      -s3 
      -s3.port=9000 
      -s3.config=/etc/seaweedfs/s3-config.json
      -filer
      -dir=/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
