services:
  # api:
  #   build:
  #     context: ./api
  #   restart: on-failure
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file: .env
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 3306
  #   ports:
  #     - "127.0.0.1:8080:8080"

  ollama-server:
    image: ollama/ollama:latest
    restart: on-failure
    ports:
      - "127.0.0.1:11434:11434"
    environment:
      - MODEL_NAME="${MODEL_NAME}"
      - OLLAMA_KEEP_ALIVE=1h
    volumes:
      - ./ollama-data:/root/.ollama
      - ./ollama-server/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash",
          "-c",
          "{ printf >&3 'GET / HTTP/1.0\\r\\n\\r\\n'; cat <&3; } 3<>/dev/tcp/localhost/11434 | grep 'Ollama is' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

  db:
    image: postgres:16
    restart: on-failure
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USR}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U ${DB_USR} -d ${DB_NAME}
      interval: 10s
      timeout: 3s
      retries: 3

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    ports:
      - "9000:9000" # S3 API
      - "9333:9333" # Server Status
      - "8888:8888" # WebUI
    volumes:
      - ./seaweed-server/filer.toml:/etc/seaweedfs/filer.toml
      # - ./sw_data:/data
    command: >
      server 
      -ip=seaweedfs
      -s3 
      -s3.port=9000 
      -master.port=9333 
      -volume.port=8080 
      -filer 
      -filer.port=8888 
      -dir=/data
    environment:
      FILE_STORAGE_ACCESS_KEY: "${STORAGE_USR}"
      FILE_STORAGE_SECRET_KEY: "${STORAGE_PWD}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
