[general]
options_for_filer_server = ""

[leveldb2]
enabled = true
dir = "/data/filerdb"

[notification.webhook]
enabled = true
endpoint = "http://api:8080/api/v1/documents/webhooks"
event_filter = ["create"]

[s3]
enabled = true
